In [1]:
import torch

#### some basic functions to create tensors

1. torch.empty()
2. torch.zeros()
3. torch.ones()
4. torch.rand()

In [3]:
x = torch.empty(1) 
print(x) # prints empty Tensor

tensor([1.0102e-38])


In [4]:
x = torch.empty(3)
print(x) # prints empty tensor (1 D vector) with 3 elements 

tensor([0., 0., 0.])


In [5]:
x = torch.empty(2,3)
print(x) #2D tensor

tensor([[7.1466e-44, 6.8664e-44, 1.1771e-43],
        [6.7262e-44, 7.7071e-44, 8.1275e-44]])


In [7]:
x = torch.empty(2,2,2)
print(x)

tensor([[[1.6706e-07, 3.3091e+21],
         [8.2288e-10, 5.4365e+22]],

        [[2.6730e-06, 8.1725e+20],
         [5.2301e+22, 6.7352e+22]]])


In [8]:
X = torch.rand(2,2) # random tensor
print(X)

tensor([[0.9058, 0.7368],
        [0.7349, 0.7836]])


In [9]:
X = torch.zeros(2,2) 
print(X)


tensor([[0., 0.],
        [0., 0.]])


In [12]:
X = torch.ones(2,2)
print(X)
print(X.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [14]:
X = torch.ones(2,2, dtype=torch.float16)
print(X)
print(X.dtype)
print(X.size())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
torch.float16
torch.Size([2, 2])


#### Create Tensor with List

In [15]:
X = torch.tensor([2.4,2.1,3.5])
print(X)

tensor([2.4000, 2.1000, 3.5000])


### addition

In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
print()
z = x + y
print(z)
print()
z = torch.add(x,y)
print(z)
print()

y.add_(x) # modifies y and adds all elements of x to y 
print(y)

tensor([[0.2299, 0.7416],
        [0.6373, 0.7987]])
tensor([[0.5559, 0.4043],
        [0.0948, 0.4070]])

tensor([[0.7858, 1.1459],
        [0.7321, 1.2057]])

tensor([[0.7858, 1.1459],
        [0.7321, 1.2057]])

tensor([[0.7858, 1.1459],
        [0.7321, 1.2057]])


### Subtraction

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x - y 
print(z)
z = torch.sub(x, y)
print(z)

tensor([[ 0.2552, -0.2919],
        [-0.3732, -0.2343]])
tensor([[ 0.2552, -0.2919],
        [-0.3732, -0.2343]])


#### Multiplication

In [22]:
z = x*y
print(z)
z = torch.mul(x,y)
print(z)

tensor([[0.6453, 0.5694],
        [0.2821, 0.2822]])
tensor([[0.6453, 0.5694],
        [0.2821, 0.2822]])


### Division

In [24]:
z = x/y 
print(z)
z = torch.div(x, y)
print(z)

tensor([[1.3722, 0.6808],
        [0.5021, 0.6456]])
tensor([[1.3722, 0.6808],
        [0.5021, 0.6456]])


In [27]:
import torch

x = torch.rand(5,3)
print(x)

print(x[:,0]) # all rows but only 0th column
print(x[1, :]) # row 1 but all columns
print(x[1,1]) # tensor at position 1,1 
print(x[1,1].item()) # tensor item at position 1,1

tensor([[0.9945, 0.6759, 0.8068],
        [0.0287, 0.3793, 0.1793],
        [0.8103, 0.7554, 0.9194],
        [0.1871, 0.7763, 0.5077],
        [0.8913, 0.4252, 0.3259]])
tensor([0.9945, 0.0287, 0.8103, 0.1871, 0.8913])
tensor([0.0287, 0.3793, 0.1793])
tensor(0.3793)
0.3793424367904663


### Reshaping Tensor

In [30]:
import torch

x = torch.rand(4,4)
print(x)
y = x.view(16)  # 1D
print(y)
print(y.size())
z = x.view(-1, 8) # will determine the correct size
print(z)
print(z.size())

tensor([[0.3350, 0.2386, 0.3949, 0.4377],
        [0.3131, 0.9794, 0.3765, 0.6301],
        [0.9232, 0.0586, 0.6116, 0.6428],
        [0.7178, 0.4789, 0.6671, 0.6051]])
tensor([0.3350, 0.2386, 0.3949, 0.4377, 0.3131, 0.9794, 0.3765, 0.6301, 0.9232,
        0.0586, 0.6116, 0.6428, 0.7178, 0.4789, 0.6671, 0.6051])
torch.Size([16])
tensor([[0.3350, 0.2386, 0.3949, 0.4377, 0.3131, 0.9794, 0.3765, 0.6301],
        [0.9232, 0.0586, 0.6116, 0.6428, 0.7178, 0.4789, 0.6671, 0.6051]])
torch.Size([2, 8])


### Converting the numpy array to tensor or vice versa

In [36]:
import torch
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy() # converting tensor to numpy array
print(b)
print(type(b))
print()

a.add_(1) # adding 1 to each element in a
print(a)
print(b) # changes in a will change b as b points to a 

print()
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1 
print(a) # adding 1 to each element in a
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### Creating tensors on GPU

In [37]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device= device) # creating tensor directly on GPU device
    y = torch.ones(5) # creating tensor first
    y = y.to(device) # then moving it to device
    z = x*y # tensor multiplication
    z = z.to("cpu") # moving tensor to cpu after computation

In [39]:
x = torch.ones(5, requires_grad = True) # It tells your tensor to calculate gradients in the optimization steps
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


#### Summary

1. Basic functions to create tensors
2. Operations on tensors: add, sub, mul, div
3. Reshaping the tensor
4. Converting numpy array to tensor and vice versa
5. Creating Tensors on GPU